### PR TITLE
Summary report

### PR DESCRIPTION
**Pull request by LMBradford**
Tests are expected to fail because the config in this branch includes a parameter not found in the test data.

Produces a single, high-level summary report for the whole project. This includes brief explanations of the methods used, number of samples passing QC (and info on which samples failed QC), number of DEGs per contrast (with figures), and biomarker calls for TGx-DDI and TGx-HDACi if biomarker analyses were run.

This branch also slightly reorganizes outputs.

### CODE REVIEW

**Comment by LMBradford** [comment]
Commit fd3a3f3d2d933ec0122b2e5890e8eff6e3018889 closes issue #148 .

**Comment by LMBradford** [comment]
Test data repo now includes the generate_summary_report parameter in config.yaml.

**Comment by LMBradford** [comment]
This PR closes issue #130 . A single DEG_count file appears in the summary folder, and DEG plots are included in summary report instead of as pngs.

**Review by mattjmeier — APPROVED** [review]
Looks fantastic!! Thanks again for this great feature.

**Pull request merged**
