### PR TITLE
Fix platefig facets

### PR DESCRIPTION
**Pull request by LMBradford**
Now all plate plots in the Studywide_Sample_QC report have left and bottom labels. 

Did this with facet_rep_wrap() from the lemon library. This required adding conda-forge::r-lemon to the reports environment.

### CODE REVIEW

**Comment by LMBradford** [comment]
image
New plot.

**Comment by mattjmeier** [comment]
That's awesome! Nice work.

It seems like the spacing is not equal for rows compared to columns. Was it before? I can't remember but it looks less like a 96 well plate to me with unequal spacing. What do you think?

**Comment by mattjmeier** [comment]
Looking at the code it's maybe the scales set to free that is allowing it to move. Is it necessary to set scales = free?

**Comment by mattjmeier** [comment]
https://rstudio-pubs-static.s3.amazonaws.com/427185_abcc25a951c9436680dc6a8fcc471ca9.html

Some of this might also be useful! Particularly the `coord_fixed(ratio=(13/12)/(9/8)`

**Comment by LMBradford** [comment]
The spacing isn't even and it's annoying me too. It wasn't even before, either, but having the left-side labels on each plate squashes them even more. They're not evenly spaced vertically, either.

scales = free is required by facet_rep_wrap to actually put the labels on each facet. I tried without but it didn't work. I tried to find a way to set height and width without any luck, but maybe the coord_fixed thing will do it! I'll try.

**Comment by LMBradford** [comment]
The spacing issue is probably fixable somehow, but I've now spent an unreasonable amount of time on it without success. 

Playing with coord_fixed does some interesting but not desirable things to the plate wells:
image


We can get labels on all axes, as shown in the comment above, using lemon (as above), or using a package called ggh4x (https://cran.r-project.org/web/packages/ggh4x/readme/README.html). In both cases, I have to use `scales = "free"` to get all the labels.

The ggh4x package includes a force_panelsizes function, which seems like it would help in sizing all the "plates" evenly, but adding it to the ggplot code (ex. `force_panelsizes(rows = unit(2, "in"), cols = unit(4, "in"))`) doesn't change anything. 

I wonder if the reason nothing changes, even with settings that should have an effect, has something to do with the fact that figure height is explicitly set in the code chunks that actually produce the figures:

I.e., these bits of code
`custom_fig_height <- ifelse(test = are_there_plates, yes = batch_length, no = 5)`

```
{r fig.height = as.numeric(custom_fig_height), eval = are_there_plates}
```

Anyway, I would like to give up on making the plate figure look fancier at this point.
I'm inclined to switch to using ggh4x instead of lemon, because it has other neat functionalities that we may want to use at some point. (https://cran.r-project.org/web/packages/ggh4x/readme/README.html)

**Comment by LMBradford** [comment]
Figures using ggh4x:
image

image

These are from the most recent bisphenols experiment. The "any samples which failed" figure gets kind of horizontally squished, but that's because the legend is large, because they used "concentration" instead of "dose" as the column name. If that makes sense.

**Review by mattjmeier — APPROVED** [review]
Great work - hopefully some day we will find a way to keep that aspect ratio fixed

**Pull request merged**
