### PR TITLE
Running fisher report

### PR DESCRIPTION
**Pull request by LMBradford**
Adds a report module for the Running Fisher test as adapted by Andrew Williams.

### CODE REVIEW

**Comment by LMBradford** [comment]
Note that tests will fail at the moment because I've added a parameter to the config that isn't in the test dataset.

**Comment by LMBradford** [comment]
This branch does not yet contain the biomarker files necessary for running the code because I do not know which ones can be made public on this repo. I will consult with Andrew.

Still to come: 
- matching by ensembl ID instead of gene symbol, which should (1) work with RNA-Seq, not just TempO-seq and (2) protect from TempO-seq using symbol aliases.
- information about which cell line or organism was used for each biomarker development, so users can tell which results are relevant for their experiment
- More explanation and formatting in the report

**Comment by LMBradford** [comment]
Test data config now has the generate_running_fisher param, but tests are failing because the biosets output files have changed (on purpose! They now properly use a lfc 1.2 cutoff). I need to find the new truth md5sums and change them in the test data set repo.

**Comment by mattjmeier** [comment]
Did the unfaceted fix work?

**Comment by LMBradford** [comment]
> Did the unfaceted fix work?

It did!

**Review by mattjmeier — APPROVED** [review]
Looks great!

**Pull request merged**
